public class TestClass1 {
    
    Public static string meth(){
        string s = 'maneesh kumar';
        list<string> lname = new list<string>();
        set<integer> sname = new set<integer>();
        map<integer,string> mname =new map<integer,string>();
        lname.add('mk');
        mname.put(1,'m');
        mname.put(2,'k');
        system.debug(mname);
        mname.remove(1);
        system.debug(lname);
        system.debug(mname);
        system.debug('kkk');
        return 'sss';
        
        
        //return integer
    }

}